### ISSUE TITLE
Feedback for “FIS Token”

### ISSUE THREAD

**Issue by pouletfritesmayo** [stafiprotocol/docs#44]
hello in your page https://docs.stafi.io/fistoken/  you write FIS currently supports the following markets.
...
...
...
kreken  !!
..
..
i was thinking krAken no ?
Have a good day Force on you ;-)

**Comment by eesignal** [comment]
Hey, thx for pointing it, this wording has been fixed.

https://github.com/stafiprotocol/docs/commit/e9d912931bc13c0853a4df389c4826dcc55bfd3b
